### ISSUE TITLE
Bug: - error Error [TypeError]: getStaticPaths is not a function

### ISSUE THREAD

**Issue by fabriguespe** [xmtp/xmtp-js#413]
### Describe the bug

In nexjs im getting this error while importing the client
```

- error Error [TypeError]: getStaticPaths is not a function
    at buildStaticPaths (/Users/fabrizioguespe/Developer/devrel/xmtp-video/my-app/node_modules/next/dist/build/utils.js:699:39)
    at Object.loadStaticPaths (/Users/fabrizioguespe/Developer/devrel/xmtp-video/my-app/node_modules/next/dist/server/dev/static-paths-worker.js:103:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: undefined
```

### Steps to reproduce the bug

I imported it at the same time of thirdweb

`
npm install @xmtp/xmtp-js @thirdweb-dev/react
`

**Comment by rygine** [comment]
@fabriguespe this doesn't seem related to XMTP, but rather Next.js.
